# Generated by Django 4.1.1 on 2022-09-22 09:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nepal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('ddgn', models.BigIntegerField(blank=True, null=True)),
                ('first_dcod', models.BigIntegerField(blank=True, null=True)),
                ('first_dist', models.CharField(blank=True, max_length=50, null=True)),
                ('first_gn_c', models.FloatField(blank=True, null=True)),
                ('first_stat', models.BigIntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('centroid_x', models.FloatField(blank=True, null=True)),
                ('centroid_y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nepal',
                'managed': False,
            },
        ),
    ]
